name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test on Go
    runs-on: ubuntu-22.04
    timeout-minutes: 1

    steps:
      - name: Checkout branch
        uses: actions/checkout@v3.1.0

      - name: Set up Go
        uses: actions/setup-go@v3.3.1
        with:
          go-version: "1.19.0"

      - name: Lint code
        run: |
          test -z $(gofmt -l .)

      - name: Validate code
        run: |
          go mod verify
          go vet ./...

      - name: Run tests
        run: |
          go test \
            -race \
            -cover \
            -coverprofile=cover.out \
            -covermode=atomic \
            ./...
          go tool cover \
            -func=cover.out
